<?php

declare(strict_types=1);

use Infrangible\CatalogFilterOffCanvas\Block\Product\ProductList\Toolbar\Filter;
use Magento\Framework\Escaper;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Escaper $escaper */
/** @var Filter $block */

$filters = $block->getActiveFilters();
?>

<button type="button" id="filtersTriggerButton" class="<?= $block->getData('triggerFilterClass'); ?>">
    <span class="<?= $block->getData('labelClass'); ?>"><?= __('Filters'); ?></span>
    <span class="<?= $block->getData('countClass'); ?>"><?= count($filters); ?></span>
</button>
